<?php

/**
 * BaseWfhRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date_applied
 * @property integer $emp_number
 * @property string $comments
 * @property string $contact_no
 * @property Employee $Employee
 * @property Doctrine_Collection $CompOff
 * @property Doctrine_Collection $Wfh
 * @property Doctrine_Collection $WfhTasks
 * @property Doctrine_Collection $WfhRequestComment
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method date                getDateApplied()       Returns the current record's "date_applied" value
 * @method integer             getEmpNumber()         Returns the current record's "emp_number" value
 * @method string              getComments()          Returns the current record's "comments" value
 * @method string              getContactNo()         Returns the current record's "contact_no" value
 * @method Employee            getEmployee()          Returns the current record's "Employee" value
 * @method Doctrine_Collection getCompOff()           Returns the current record's "CompOff" collection
 * @method Doctrine_Collection getWfh()               Returns the current record's "Wfh" collection
 * @method Doctrine_Collection getWfhTasks()          Returns the current record's "WfhTasks" collection
 * @method Doctrine_Collection getWfhRequestComment() Returns the current record's "WfhRequestComment" collection
 * @method WfhRequest          setId()                Sets the current record's "id" value
 * @method WfhRequest          setDateApplied()       Sets the current record's "date_applied" value
 * @method WfhRequest          setEmpNumber()         Sets the current record's "emp_number" value
 * @method WfhRequest          setComments()          Sets the current record's "comments" value
 * @method WfhRequest          setContactNo()         Sets the current record's "contact_no" value
 * @method WfhRequest          setEmployee()          Sets the current record's "Employee" value
 * @method WfhRequest          setCompOff()           Sets the current record's "CompOff" collection
 * @method WfhRequest          setWfh()               Sets the current record's "Wfh" collection
 * @method WfhRequest          setWfhTasks()          Sets the current record's "WfhTasks" collection
 * @method WfhRequest          setWfhRequestComment() Sets the current record's "WfhRequestComment" collection
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWfhRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_wfh_request');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('date_applied', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_number', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('comments', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('contact_no', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('CompOff', array(
             'local' => 'id',
             'foreign' => 'wfh_request_id'));

        $this->hasMany('Wfh', array(
             'local' => 'id',
             'foreign' => 'wfh_request_id'));

        $this->hasMany('WfhTasks', array(
             'local' => 'id',
             'foreign' => 'wfh_request_id'));

        $this->hasMany('WfhRequestComment', array(
             'local' => 'id',
             'foreign' => 'wfh_request_id'));
    }
}