<?php

/**
 * BaseCompoffExtensionRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entitlement_id
 * @property datetime $extension_date
 * @property string $comments
 * @property integer $status
 * @property LeaveEntitlement $LeaveEntitlement
 * 
 * @method integer                 getId()               Returns the current record's "id" value
 * @method integer                 getEntitlementId()    Returns the current record's "entitlement_id" value
 * @method datetime                getExtensionDate()    Returns the current record's "extension_date" value
 * @method string                  getComments()         Returns the current record's "comments" value
 * @method integer                 getStatus()           Returns the current record's "status" value
 * @method LeaveEntitlement        getLeaveEntitlement() Returns the current record's "LeaveEntitlement" value
 * @method CompoffExtensionRequest setId()               Sets the current record's "id" value
 * @method CompoffExtensionRequest setEntitlementId()    Sets the current record's "entitlement_id" value
 * @method CompoffExtensionRequest setExtensionDate()    Sets the current record's "extension_date" value
 * @method CompoffExtensionRequest setComments()         Sets the current record's "comments" value
 * @method CompoffExtensionRequest setStatus()           Sets the current record's "status" value
 * @method CompoffExtensionRequest setLeaveEntitlement() Sets the current record's "LeaveEntitlement" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompoffExtensionRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_compoff_request_extension');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('entitlement_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('extension_date', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('comments', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 6, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LeaveEntitlement', array(
             'local' => 'entitlement_id',
             'foreign' => 'id'));
    }
}