<?php

/**
 * BaseLeaveConditions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $reviewval_date
 * @property datetime $date
 * @property string $conditions
 * @property int $leave_id
 * @property Leave $Leave
 * 
 * @method integer         getId()             Returns the current record's "id" value
 * @method date            getReviewvalDate()  Returns the current record's "reviewval_date" value
 * @method datetime        getDate()           Returns the current record's "date" value
 * @method string          getConditions()     Returns the current record's "conditions" value
 * @method int             getLeaveId()        Returns the current record's "leave_id" value
 * @method Leave           getLeave()          Returns the current record's "Leave" value
 * @method LeaveConditions setId()             Sets the current record's "id" value
 * @method LeaveConditions setReviewvalDate()  Sets the current record's "reviewval_date" value
 * @method LeaveConditions setDate()           Sets the current record's "date" value
 * @method LeaveConditions setConditions()     Sets the current record's "conditions" value
 * @method LeaveConditions setLeaveId()        Sets the current record's "leave_id" value
 * @method LeaveConditions setLeave()          Sets the current record's "Leave" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveConditions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_conditions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('reviewval_date', 'date', null, array(
             'type' => 'date',
             'unsigned' => false,
             'notnull' => false,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('conditions', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('leave_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Leave', array(
             'local' => 'leave_id',
             'foreign' => 'id'));
    }
}