<?php

/**
 * BaseLeaveTasks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $leave_request_id
 * @property integer $comp_off_id
 * @property string $task_name
 * @property integer $contact_emp_number
 * @property string $task_type
 * @property integer $status
 * @property LeaveRequest $LeaveRequest
 * @property Employee $Employee
 * 
 * @method integer      getId()                 Returns the current record's "id" value
 * @method integer      getLeaveRequestId()     Returns the current record's "leave_request_id" value
 * @method integer      getCompOffId()          Returns the current record's "comp_off_id" value
 * @method string       getTaskName()           Returns the current record's "task_name" value
 * @method integer      getContactEmpNumber()   Returns the current record's "contact_emp_number" value
 * @method string       getTaskType()           Returns the current record's "task_type" value
 * @method integer      getStatus()             Returns the current record's "status" value
 * @method LeaveRequest getLeaveRequest()       Returns the current record's "LeaveRequest" value
 * @method Employee     getEmployee()           Returns the current record's "Employee" value
 * @method LeaveTasks   setId()                 Sets the current record's "id" value
 * @method LeaveTasks   setLeaveRequestId()     Sets the current record's "leave_request_id" value
 * @method LeaveTasks   setCompOffId()          Sets the current record's "comp_off_id" value
 * @method LeaveTasks   setTaskName()           Sets the current record's "task_name" value
 * @method LeaveTasks   setContactEmpNumber()   Sets the current record's "contact_emp_number" value
 * @method LeaveTasks   setTaskType()           Sets the current record's "task_type" value
 * @method LeaveTasks   setStatus()             Sets the current record's "status" value
 * @method LeaveTasks   setLeaveRequest()       Sets the current record's "LeaveRequest" value
 * @method LeaveTasks   setEmployee()           Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveTasks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_tasks');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('leave_request_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('comp_off_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('task_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('contact_emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('task_type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LeaveRequest', array(
             'local' => 'leave_request_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Employee', array(
             'local' => 'contact_emp_number',
             'foreign' => 'emp_number'));
    }
}