<?php

/**
 * BaseCompOff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property decimal $length_hours
 * @property decimal $length_days
 * @property integer $status
 * @property integer $compoff_request_id
 * @property integer $emp_number
 * @property time $start_time
 * @property time $end_time
 * @property int $duration_type
 * @property date $compoff_request_date
 * @property int $leave_entitlement_id
 * @property Employee $Employee
 * @property CompoffRequest $CompoffRequest
 * @property Doctrine_Collection $CompoffComment
 * @property WfhRequest $WfhRequest
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method date                getDate()                 Returns the current record's "date" value
 * @method decimal             getLengthHours()          Returns the current record's "length_hours" value
 * @method decimal             getLengthDays()           Returns the current record's "length_days" value
 * @method integer             getStatus()               Returns the current record's "status" value
 * @method integer             getCompoffRequestId()     Returns the current record's "compoff_request_id" value
 * @method integer             getEmpNumber()            Returns the current record's "emp_number" value
 * @method time                getStartTime()            Returns the current record's "start_time" value
 * @method time                getEndTime()              Returns the current record's "end_time" value
 * @method int                 getDurationType()         Returns the current record's "duration_type" value
 * @method date                getCompoffRequestDate()   Returns the current record's "compoff_request_date" value
 * @method int                 getLeaveEntitlementId()   Returns the current record's "leave_entitlement_id" value
 * @method Employee            getEmployee()             Returns the current record's "Employee" value
 * @method CompoffRequest      getCompoffRequest()       Returns the current record's "CompoffRequest" value
 * @method Doctrine_Collection getCompoffComment()       Returns the current record's "CompoffComment" collection
 * @method WfhRequest          getWfhRequest()           Returns the current record's "WfhRequest" value
 * @method CompOff             setId()                   Sets the current record's "id" value
 * @method CompOff             setDate()                 Sets the current record's "date" value
 * @method CompOff             setLengthHours()          Sets the current record's "length_hours" value
 * @method CompOff             setLengthDays()           Sets the current record's "length_days" value
 * @method CompOff             setStatus()               Sets the current record's "status" value
 * @method CompOff             setCompoffRequestId()     Sets the current record's "compoff_request_id" value
 * @method CompOff             setEmpNumber()            Sets the current record's "emp_number" value
 * @method CompOff             setStartTime()            Sets the current record's "start_time" value
 * @method CompOff             setEndTime()              Sets the current record's "end_time" value
 * @method CompOff             setDurationType()         Sets the current record's "duration_type" value
 * @method CompOff             setCompoffRequestDate()   Sets the current record's "compoff_request_date" value
 * @method CompOff             setLeaveEntitlementId()   Sets the current record's "leave_entitlement_id" value
 * @method CompOff             setEmployee()             Sets the current record's "Employee" value
 * @method CompOff             setCompoffRequest()       Sets the current record's "CompoffRequest" value
 * @method CompOff             setCompoffComment()       Sets the current record's "CompoffComment" collection
 * @method CompOff             setWfhRequest()           Sets the current record's "WfhRequest" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompOff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_compoff');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('length_hours', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '4',
             ));
        $this->hasColumn('length_days', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '4',
             ));
        $this->hasColumn('status', 'integer', 6, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('compoff_request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('duration_type', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('compoff_request_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('leave_entitlement_id', 'int', 11, array(
             'type' => 'int',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('CompoffRequest', array(
             'local' => 'compoff_request_id',
             'foreign' => 'id'));

        $this->hasMany('CompoffComment', array(
             'local' => 'id',
             'foreign' => 'compoff_id'));

        $this->hasOne('WfhRequest', array(
             'local' => 'wfh_request_id',
             'foreign' => 'id'));
    }
}