<?php

/**
 * BaseWfh
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property decimal $length_hours
 * @property decimal $length_days
 * @property integer $status
 * @property integer $wfh_request_id
 * @property integer $emp_number
 * @property time $start_time
 * @property time $end_time
 * @property int $duration_type
 * @property date $wfh_request_date
 * @property Employee $Employee
 * @property WfhRequest $WfhRequest
 * @property Doctrine_Collection $WfhComment
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method date                getDate()             Returns the current record's "date" value
 * @method decimal             getLengthHours()      Returns the current record's "length_hours" value
 * @method decimal             getLengthDays()       Returns the current record's "length_days" value
 * @method integer             getStatus()           Returns the current record's "status" value
 * @method integer             getWfhRequestId()     Returns the current record's "wfh_request_id" value
 * @method integer             getEmpNumber()        Returns the current record's "emp_number" value
 * @method time                getStartTime()        Returns the current record's "start_time" value
 * @method time                getEndTime()          Returns the current record's "end_time" value
 * @method int                 getDurationType()     Returns the current record's "duration_type" value
 * @method date                getWfhRequestDate()   Returns the current record's "wfh_request_date" value
 * @method Employee            getEmployee()         Returns the current record's "Employee" value
 * @method WfhRequest          getWfhRequest()       Returns the current record's "WfhRequest" value
 * @method Doctrine_Collection getWfhComment()       Returns the current record's "WfhComment" collection
 * @method Wfh                 setId()               Sets the current record's "id" value
 * @method Wfh                 setDate()             Sets the current record's "date" value
 * @method Wfh                 setLengthHours()      Sets the current record's "length_hours" value
 * @method Wfh                 setLengthDays()       Sets the current record's "length_days" value
 * @method Wfh                 setStatus()           Sets the current record's "status" value
 * @method Wfh                 setWfhRequestId()     Sets the current record's "wfh_request_id" value
 * @method Wfh                 setEmpNumber()        Sets the current record's "emp_number" value
 * @method Wfh                 setStartTime()        Sets the current record's "start_time" value
 * @method Wfh                 setEndTime()          Sets the current record's "end_time" value
 * @method Wfh                 setDurationType()     Sets the current record's "duration_type" value
 * @method Wfh                 setWfhRequestDate()   Sets the current record's "wfh_request_date" value
 * @method Wfh                 setEmployee()         Sets the current record's "Employee" value
 * @method Wfh                 setWfhRequest()       Sets the current record's "WfhRequest" value
 * @method Wfh                 setWfhComment()       Sets the current record's "WfhComment" collection
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWfh extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_wfh');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('length_hours', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '4',
             ));
        $this->hasColumn('length_days', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '4',
             ));
        $this->hasColumn('status', 'integer', 6, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('wfh_request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('duration_type', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('wfh_request_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('WfhRequest', array(
             'local' => 'wfh_request_id',
             'foreign' => 'id'));

        $this->hasMany('WfhComment', array(
             'local' => 'id',
             'foreign' => 'Wfh_id'));
    }
}