<?php

/**
 * BaseCompoffRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date_applied
 * @property integer $emp_number
 * @property integer $called_emp_number
 * @property string $comments
 * @property string $work_type
 * @property Employee $Employee
 * @property Doctrine_Collection $CompOff
 * @property Doctrine_Collection $CompoffTasks
 * @property Doctrine_Collection $CompoffRequestComment
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method date                getDateApplied()           Returns the current record's "date_applied" value
 * @method integer             getEmpNumber()             Returns the current record's "emp_number" value
 * @method integer             getCalledEmpNumber()       Returns the current record's "called_emp_number" value
 * @method string              getComments()              Returns the current record's "comments" value
 * @method string              getWorkType()              Returns the current record's "work_type" value
 * @method Employee            getEmployee()              Returns the current record's "Employee" value
 * @method Doctrine_Collection getCompOff()               Returns the current record's "CompOff" collection
 * @method Doctrine_Collection getCompoffTasks()          Returns the current record's "CompoffTasks" collection
 * @method Doctrine_Collection getCompoffRequestComment() Returns the current record's "CompoffRequestComment" collection
 * @method CompoffRequest      setId()                    Sets the current record's "id" value
 * @method CompoffRequest      setDateApplied()           Sets the current record's "date_applied" value
 * @method CompoffRequest      setEmpNumber()             Sets the current record's "emp_number" value
 * @method CompoffRequest      setCalledEmpNumber()       Sets the current record's "called_emp_number" value
 * @method CompoffRequest      setComments()              Sets the current record's "comments" value
 * @method CompoffRequest      setWorkType()              Sets the current record's "work_type" value
 * @method CompoffRequest      setEmployee()              Sets the current record's "Employee" value
 * @method CompoffRequest      setCompOff()               Sets the current record's "CompOff" collection
 * @method CompoffRequest      setCompoffTasks()          Sets the current record's "CompoffTasks" collection
 * @method CompoffRequest      setCompoffRequestComment() Sets the current record's "CompoffRequestComment" collection
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompoffRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_compoff_request');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('date_applied', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_number', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('called_emp_number', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('comments', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('work_type', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('CompOff', array(
             'local' => 'id',
             'foreign' => 'compoff_request_id'));

        $this->hasMany('CompoffTasks', array(
             'local' => 'id',
             'foreign' => 'compoff_request_id'));

        $this->hasMany('CompoffRequestComment', array(
             'local' => 'id',
             'foreign' => 'compoff_request_id'));
    }
}