<?php

/**
 * BaseWfhTasks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $wfh_request_id
 * @property string $task_name
 * @property WfhRequest $WfhRequest
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method integer    getWfhRequestId()   Returns the current record's "wfh_request_id" value
 * @method string     getTaskName()       Returns the current record's "task_name" value
 * @method WfhRequest getWfhRequest()     Returns the current record's "WfhRequest" value
 * @method WfhTasks   setId()             Sets the current record's "id" value
 * @method WfhTasks   setWfhRequestId()   Sets the current record's "wfh_request_id" value
 * @method WfhTasks   setTaskName()       Sets the current record's "task_name" value
 * @method WfhTasks   setWfhRequest()     Sets the current record's "WfhRequest" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWfhTasks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_wfh_tasks');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('wfh_request_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('task_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WfhRequest', array(
             'local' => 'wfh_request_id',
             'foreign' => 'id'));
    }
}