<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/17 06:53:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=perennial_hrm',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
