<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/02/21 14:53:02
sfConfig::add(array(
  'mod_performancetracker_enabled' => true,
  'mod_performancetracker_view_class' => 'sfPHP',
));
