<?php

/**
 * CompoffExtensionRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompoffExtensionRequestTable extends PluginCompoffExtensionRequestTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompoffExtensionRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompoffExtensionRequest');
    }
}