<?php

/**
 * CompoffRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompoffRequestTable extends PluginCompoffRequestTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompoffRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompoffRequest');
    }
}