<?php

/**
 * CompoffTasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompoffTasksTable extends PluginCompoffTasksTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompoffTasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompoffTasks');
    }
}