<?php

/**
 * CompOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompOffTable extends PluginCompOffTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompOff');
    }
}