<?php

/**
 * CompoffCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompoffCommentTable extends PluginCompoffCommentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompoffCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompoffComment');
    }
}