<?php

/**
 * LeaveConditionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveConditionsTable extends PluginLeaveConditionsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveConditionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveConditions');
    }
}