<?php

/**
 * LeaveTasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveTasksTable extends PluginLeaveTasksTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveTasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveTasks');
    }
}