<?php

/**
 * LeaveRequestConditionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveRequestConditionsTable extends PluginLeaveRequestConditionsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveRequestConditionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveRequestConditions');
    }
}