<?php

/**
 * WfhCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WfhCommentTable extends PluginWfhCommentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WfhCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WfhComment');
    }
}