<?php

/**
 * WfhRequestCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WfhRequestCommentTable extends PluginWfhRequestCommentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WfhRequestCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WfhRequestComment');
    }
}