<?php

/**
 * WfhTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WfhTable extends PluginWfhTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WfhTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wfh');
    }
}