<?php

/**
 * PluginEmployeeImmigrationRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEmployeeImmigrationRecord extends BaseEmployeeImmigrationRecord
{
    
    const TYPE_PASSPORT = 1;
    const TYPE_VISA = 2;
    const TYPE_LICENSE = 2;
    const TYPE_Adhar_Card = 3;
    const TYPE_Election_Card = 4;
    const TYPE_PAN_Card=5;

}