<?php

/**
 * PluginCompoffRequestCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompoffRequestCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompoffRequestCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompoffRequestComment');
    }
}