<?php

/**
 * PluginLeaveTasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveTasksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveTasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveTasks');
    }
}