<?php

/**
 * PluginWfhTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWfhTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWfhTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWfh');
    }
}