<?php

/**
 * PluginWfhCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWfhCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWfhCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWfhComment');
    }
}