<?php

/**
 * PluginCompOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompOffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompOff');
    }
}