<?php

/**
 * PluginCompoffExtensionRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCompoffExtensionRequest extends BaseCompoffExtensionRequest
{ 
    public $employeeService;
     public function getEmployeeService() {
        if (is_null($this->employeeService)) {
            $empService = new EmployeeService();
            $empService->setEmployeeDao(new EmployeeDao());
            $this->employeeService = $empService;
        }
        return $this->employeeService;
    }
    
    public function getEmpDetails(){
        $empNumber = $this->getEmpNumber();
        $employee = $this->getEmployeeService()->getEmployee($empNumber);
        $name = $employee->getFullName();
        return $name;
    }
    public function getStatusDetails(){
        $status = $this->getStatus();
        if($status == 0){
            $txtStatus = 'Pending';
        }
        elseif ($status == 1) {
        $txtStatus = 'Cancelled';
    }
    else{
        $txtStatus = 'Approved';
    }
        return $txtStatus;
    }
    public function getExtensionRequestActions(){
        $actions = array();
        if($this->getStatus() == 0){
            $actions[1] ='Cancel';
            $actions[2] ='Approve';
        }
        elseif ($this->getStatus()==2) {
        $actions[1] = 'Cancel';
    }
    return $actions;
    }
    public function getDate(){
        $date = $this->getExtensionDate();
        $newdate = date('d-m-Y',strtotime($date));
        return $newdate;
    }
}