<?php

/**
 * PluginCompoffExtensionRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompoffExtensionRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompoffExtensionRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompoffExtensionRequest');
    }
}