<?php

/**
 * PluginWfhRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWfhRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWfhRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWfhRequest');
    }
}