<?php

/**
 * PluginWfhRequestCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWfhRequestCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWfhRequestCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWfhRequestComment');
    }
}