<?php

/**
 * PluginLeaveRequestConditionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveRequestConditionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveRequestConditionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveRequestConditions');
    }
}