<?php

/**
 * PluginCompoffCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompoffCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompoffCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompoffComment');
    }
}