<?php

/**
 * PluginCompoffTasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompoffTasksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompoffTasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompoffTasks');
    }
}